# Generated by Django 3.1.7 on 2021-04-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210325_1012'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
