# Generated by Django 3.1.7 on 2021-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
