# Generated by Django 3.1.7 on 2021-03-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210316_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='../media/photos/%Y/%m/%d/'),
        ),
    ]
