# Generated by Django 3.1.7 on 2021-03-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210303_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='todos',
            field=models.ManyToManyField(null=True, related_name='all_todo', to='todo_app.Todo'),
        ),
    ]
