# Generated by Django 3.1.7 on 2021-03-07 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='film_category', to='film_app.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
