# Generated by Django 3.1.7 on 2021-03-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_auto_20210307_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='available_in_country',
        ),
    ]
