# Generated by Django 3.1.7 on 2021-03-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0003_remove_film_available_in_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='available_in_country',
            field=models.ManyToManyField(related_name='film_country', to='film_app.Country'),
        ),
    ]
