# Generated by Django 3.1.7 on 2021-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210324_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[(0, 'Visa'), (1, 'Misrad Hapnim'), (2, 'Healthcare'), (3, 'Mariage'), (4, 'Police'), (5, 'General')], default=5, max_length=30),
        ),
    ]
