# Generated by Django 3.1.7 on 2021-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210325_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Publish')], default=0, null=True),
        ),
    ]
