# Generated by Django 3.1.7 on 2021-03-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210325_1012'),
        ('blog', '0012_auto_20210329_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='blog_like', to='accounts.Profile'),
        ),
    ]
