# Generated by Django 3.1.7 on 2021-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210325_1012'),
        ('blog', '0013_auto_20210330_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='blog_like', to='accounts.Profile'),
        ),
    ]
