# Generated by Django 3.1.7 on 2021-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210325_1012'),
        ('blog', '0014_auto_20210405_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='blog_like', to='accounts.Profile'),
        ),
    ]
